version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.5
      - image: mariadb:5.5.56
        environment:
          MYSQL_ROOT_PASSWORD: ic
          MYSQL_DATABASE: ci_db
          MYSQL_USER: ci
          MYSQL_PASSWORD: ic

    working_directory: /go/src/github.com/gcjensen/splend-api

    steps:
      - checkout
      - run:
          name: Wait for MySQL container to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: Get dependencies
          command: |
            go get -v -t ./...
      - run:
          name: Set up config and install mysql CLI
          command: |
            sudo mkdir /etc/splend
            sudo scp .circleci/splend-api.yaml /etc/splend/
            sudo apt-get update
            sudo apt install -y default-mysql-client
            mysql -h 127.0.0.1 -u ci -pic ci_db < meta/schema.sql
      - run:
          name: Run tests
          command: |
            go test ./...
      - run:
          name: Lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0
            $(go env GOPATH)/bin/golangci-lint run -v

